/// <reference types="@nomicfoundation/hardhat-ethers" />
/// <reference types="@nomicfoundation/hardhat-ethers-chai-matchers" />
// Runs against a local Tempo node (`anvil --network tempo`, see
// DEVELOPMENT_GUIDE.md): the SP1 v6.1.0 Groth16 verifier, and the bridged
// token created through Tempo's TIP20Factory precompile with pathUSD as its
// quote token.
import { expect } from "chai";
import { randomBytes } from "crypto";
import { readFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import hre from "hardhat";
import {
  bridgeHeadNoriSP1HeliosProgramVk,
  decodeConsensusMptProof,
  extractEthProofQueueAddressFromSP1Proof,
  sp1Groth16ProofBytes,
  sp1ProgramVkey,
  sp1PublicValues,
} from "@nori-zk/tempo-zk-utils";
import {
  ITIP20__factory,
  ITIP20Factory__factory,
  NoriTempoTokenBridge__factory,
} from "../types/ethers-contracts/index.js";
import { SP1Verifier__factory } from "../types/ethers-contracts/factories/lib/sp1-contracts/contracts/src/v6.1.0/SP1VerifierGroth16.sol/SP1Verifier__factory.js";
import { buildExampleProofSeriesCreateArguments } from "./constructExampleProofs.js";
import {
  MAX_COLLECTION_KEYS,
  MAX_TREE_DEPTH,
  MAX_U64,
  PACKED_STATE_OFFSETS,
  PACKED_STATE_SLOT,
  PAUSE_KEY,
  PAUSE_STATE_PAUSED,
  PAUSE_STATE_UNPAUSED,
  PROOF_OUTPUTS_SIZE,
  PROOF_QUEUE_BATCH_OFFSETS,
  PROOF_QUEUE_BATCHES_SLOT,
} from "../contracts/NoriTempoTokenBridge.const.js";
import {
  ISSUER_ROLE_NAME,
  PATH_USD_ADDRESS,
  PAUSE_ROLE_NAME,
  TIP20_DECIMALS,
  TIP20_FACTORY_ADDRESS,
  UNPAUSE_ROLE_NAME,
} from "../contracts/interfaces/ITIP20.const.js";

const { ethers } = await hre.network.getOrCreate();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** The integration test data's chained proofs, as `update` takes them. */
const EXAMPLE_SERIES = buildExampleProofSeriesCreateArguments();
const EXAMPLE_PROOFS = EXAMPLE_SERIES.map((example) => ({
  proof: sp1Groth16ProofBytes(example),
  sp1PublicInputs: sp1PublicValues(example),
  decoded: decodeConsensusMptProof(example),
}));

/** The bridge's start values, decoded from the first example proof. */
const INITIAL_STORE_HASH = EXAMPLE_PROOFS[0].decoded.inputStoreHash;
const ETH_PROOF_QUEUE_ADDRESS = extractEthProofQueueAddressFromSP1Proof(EXAMPLE_SERIES[0]);
const TEST_ETH_TOKEN_BRIDGE_ADDRESS = "0x" + "22".repeat(20);

const ISSUER_ROLE = ethers.id(ISSUER_ROLE_NAME);

interface RequestLeafVector {
  name: string;
  target: string;
  collectionKeysCount: number;
  collectionKeys: [string, string];
  value: string;
  leaf: string;
}

interface ProofOutputsVector {
  name: string;
  inputSlot: string;
  inputStoreHash: string;
  outputSlot: string;
  outputStoreHash: string;
  executionStateRoot: string;
  verifiedRequestsRoot: string;
  nextSyncCommitteeHash: string;
  proofRequestQueueAddress: string;
  inputQueueCursor: string;
  outputQueueCursor: string;
  outputBlockNumber: string;
  bytes: string;
}

const readVectors = <T>(file: string): T =>
  JSON.parse(readFileSync(path.resolve(__dirname, "test-vectors/proof-request-queue", file), "utf8")) as T;

/** nori-bridge-head's request leaves, generated by the guest's own `hash_request_leaf`. */
const REQUEST_LEAF_VECTORS = readVectors<RequestLeafVector[]>("request-leaf-vectors.json");
/** nori-bridge-head's `ProofOutputs` encodings, generated by the guest's own `to_bytes`. */
const PROOF_OUTPUTS_VECTORS = readVectors<ProofOutputsVector[]>("proof-outputs-vectors.json");

const repeat = (byte: number) => "0x" + byte.toString(16).padStart(2, "0").repeat(32);

interface Request {
  target: string;
  collectionKeysCount: number;
  collectionKeys: [string, string];
  value: bigint;
}

/** `requestLeafHash`, in TypeScript, for building batch trees in tests. */
function leafHash(r: Request): string {
  const key0 = ethers.getBytes(r.collectionKeys[0]);
  const key1 = ethers.getBytes(r.collectionKeys[1]);
  const value = ethers.getBytes(ethers.toBeHex(r.value, 32));
  const field = (bytes: Uint8Array) => ethers.concat([bytes.slice(1), new Uint8Array(1)]);
  return ethers.sha256(
    ethers.concat([
      r.target,
      new Uint8Array([r.collectionKeysCount, key0[0], key1[0], value[0]]),
      new Uint8Array(8),
      field(key0),
      field(key1),
      field(value),
    ])
  );
}

const node = (left: string, right: string) => ethers.sha256(ethers.concat([left, right]));

const word = (value: bigint) => ethers.toBeHex(value, 32);

describe("NoriTempoTokenBridge", () => {
  /**
   * A bridge deployed with the first example proof's input store hash and
   * queue address: the SP1 verifier, the bridged token created through
   * TIP20Factory with the deployer as admin, and ISSUER_ROLE granted to the
   * bridge.
   */
  async function deployBridge(
    overrides: {
      vkey?: string;
      ethProofQueueAddress?: string;
      latestHeliosStoreInputHash?: string;
    } = {}
  ) {
    const [deployer, recipient, other] = await ethers.getSigners();
    const verifier = await new SP1Verifier__factory(deployer).deploy();

    const factory = ITIP20Factory__factory.connect(TIP20_FACTORY_ADDRESS, deployer);
    const salt = ethers.hexlify(randomBytes(32));
    const tokenArgs = ["nETH", "nETH", "ETH", PATH_USD_ADDRESS, deployer.address, salt] as const;
    const tokenAddress = await factory.createToken.staticCall(...tokenArgs);
    await (await factory.createToken(...tokenArgs)).wait();
    const token = ITIP20__factory.connect(tokenAddress, deployer);

    const bridge = await new NoriTempoTokenBridge__factory(deployer).deploy(
      await verifier.getAddress(),
      overrides.vkey ?? bridgeHeadNoriSP1HeliosProgramVk,
      tokenAddress,
      overrides.latestHeliosStoreInputHash ?? INITIAL_STORE_HASH,
      TEST_ETH_TOKEN_BRIDGE_ADDRESS,
      overrides.ethProofQueueAddress ?? ETH_PROOF_QUEUE_ADDRESS
    );
    await bridge.waitForDeployment();
    await (await token.grantRole(ISSUER_ROLE, await bridge.getAddress())).wait();
    return { bridge, verifier, token, deployer, recipient, other };
  }

  /**
   * Plants the bridge's packed state word (slot 2) with `anvil_setStorageAt`,
   * replacing the given fields and keeping the rest.
   */
  async function plantPackedState(
    bridgeAddress: string,
    fields: { latestHead?: bigint; queueCursor?: bigint; proofQueueBatchCount?: bigint }
  ) {
    const provider = ethers.provider;
    const packed = BigInt(await provider.getStorage(bridgeAddress, PACKED_STATE_SLOT));
    const latestHead = fields.latestHead ?? (packed >> PACKED_STATE_OFFSETS.latestHead) & MAX_U64;
    const queueCursor = fields.queueCursor ?? (packed >> PACKED_STATE_OFFSETS.queueCursor) & MAX_U64;
    const proofQueueBatchCount =
      fields.proofQueueBatchCount ?? (packed >> PACKED_STATE_OFFSETS.proofQueueBatchCount) & MAX_U64;
    const planted =
      (latestHead << PACKED_STATE_OFFSETS.latestHead) |
      (queueCursor << PACKED_STATE_OFFSETS.queueCursor) |
      (proofQueueBatchCount << PACKED_STATE_OFFSETS.proofQueueBatchCount);
    await provider.send("anvil_setStorageAt", [bridgeAddress, word(PACKED_STATE_SLOT), word(planted)]);
  }

  /**
   * Plants committed proof queue batches in the bridge's storage with
   * `anvil_setStorageAt`: each entry at `keccak256(index, 3)` and the count
   * in slot 2.
   */
  async function plantProofQueueBatches(
    bridgeAddress: string,
    batches: Array<{ root: string; inputQueueCursor: bigint; outputQueueCursor: bigint; outputBlockNumber: bigint }>
  ) {
    const provider = ethers.provider;
    for (const [i, batch] of batches.entries()) {
      const base = BigInt(
        ethers.keccak256(ethers.AbiCoder.defaultAbiCoder().encode(["uint64", "uint256"], [i, PROOF_QUEUE_BATCHES_SLOT]))
      );
      const tempoBlockNumber = 1n;
      const packed =
        (batch.outputBlockNumber << PROOF_QUEUE_BATCH_OFFSETS.outputBlockNumber) |
        (batch.inputQueueCursor << PROOF_QUEUE_BATCH_OFFSETS.inputQueueCursor) |
        (batch.outputQueueCursor << PROOF_QUEUE_BATCH_OFFSETS.outputQueueCursor) |
        (tempoBlockNumber << PROOF_QUEUE_BATCH_OFFSETS.tempoBlockNumber);
      await provider.send("anvil_setStorageAt", [bridgeAddress, word(base), batch.root]);
      await provider.send("anvil_setStorageAt", [bridgeAddress, word(base + 1n), word(packed)]);
    }
    await plantPackedState(bridgeAddress, { proofQueueBatchCount: BigInt(batches.length) });
  }

  describe("example proofs", () => {
    it("are made for the integrity program vkey", () => {
      for (const example of EXAMPLE_SERIES) expect(sp1ProgramVkey(example)).to.equal(bridgeHeadNoriSP1HeliosProgramVk);
    });

    it("chain: each proof resumes where the previous one ends", () => {
      for (let i = 1; i < EXAMPLE_PROOFS.length; i++) {
        const previous = EXAMPLE_PROOFS[i - 1].decoded;
        const current = EXAMPLE_PROOFS[i].decoded;
        expect(current.inputSlot).to.equal(previous.outputSlot);
        expect(current.inputStoreHash).to.equal(previous.outputStoreHash);
        expect(current.inputQueueCursor).to.equal(previous.outputQueueCursor);
      }
    });

    it("drain no proof requests", () => {
      for (const { decoded } of EXAMPLE_PROOFS) {
        expect(decoded.inputQueueCursor).to.equal(0n);
        expect(decoded.outputQueueCursor).to.equal(0n);
      }
    });
  });

  describe("deploy", () => {
    it("starts at head 0 and cursor 0 with the given store hash and addresses", async () => {
      const { bridge, verifier, token } = await deployBridge();
      const state = await bridge.state();
      expect(state.latestHead).to.equal(0n);
      expect(state.queueCursor).to.equal(0n);
      expect(state.proofQueueBatchCount).to.equal(0n);
      expect(state.verifiedStateRoot).to.equal(ethers.ZeroHash);
      expect(state.latestHeliosStoreInputHash).to.equal(INITIAL_STORE_HASH);
      expect(state.noriBridgeVk).to.equal(bridgeHeadNoriSP1HeliosProgramVk);
      expect(state.ethProofQueueAddress).to.equal(ethers.getAddress(ETH_PROOF_QUEUE_ADDRESS));
      expect(state.ethTokenBridgeAddress).to.equal(ethers.getAddress(TEST_ETH_TOKEN_BRIDGE_ADDRESS));
      expect(await bridge.verifier()).to.equal(await verifier.getAddress());
      expect(await bridge.token()).to.equal(await token.getAddress());
    });

    it("rejects a zero address", async () => {
      const [deployer] = await ethers.getSigners();
      const factory = new NoriTempoTokenBridge__factory(deployer);
      await expect(
        factory.deploy(
          ethers.ZeroAddress,
          bridgeHeadNoriSP1HeliosProgramVk,
          PATH_USD_ADDRESS,
          INITIAL_STORE_HASH,
          TEST_ETH_TOKEN_BRIDGE_ADDRESS,
          ETH_PROOF_QUEUE_ADDRESS
        )
      ).to.be.revertedWithCustomError(factory, "ZeroAddress");
    });
  });

  describe("update", () => {
    it("selects the v6.1.0 verifier with every example proof", async () => {
      const { verifier } = await deployBridge();
      const selector = (await verifier.VERIFIER_HASH()).slice(0, 10);
      expect(selector).to.equal("0x4388a21c");
      for (const proof of EXAMPLE_PROOFS) expect(proof.proof.slice(0, 10)).to.equal(selector);
    });

    it("applies the four chained example proofs in order", async () => {
      const { bridge } = await deployBridge();
      for (const proof of EXAMPLE_PROOFS) {
        const decoded = await bridge.decodeProofOutputs(proof.sp1PublicInputs);
        await expect(bridge.update(proof.proof, proof.sp1PublicInputs))
          .to.emit(bridge, "UpdateApplied")
          .withArgs(decoded.outputSlot, decoded.outputQueueCursor, decoded.executionStateRoot, 0n);
        expect(await bridge.latestHead()).to.equal(decoded.outputSlot);
        expect(await bridge.latestHeliosStoreInputHash()).to.equal(decoded.outputStoreHash);
        expect(await bridge.verifiedStateRoot()).to.equal(decoded.executionStateRoot);
        expect(await bridge.queueCursor()).to.equal(decoded.outputQueueCursor);
      }
      // The example proofs drain no requests: no proof queue batch is committed.
      expect(await bridge.proofQueueBatchCount()).to.equal(0n);
    });

    it("rejects an example proof whose public values were changed", async () => {
      const { bridge } = await deployBridge();
      const { proof, sp1PublicInputs } = EXAMPLE_PROOFS[0];
      const tampered = ethers.getBytes(sp1PublicInputs);
      tampered[219] ^= 1;
      await expect(bridge.update(proof, tampered)).to.be.revertedWithCustomError(bridge, "ProofVerificationFailed");
    });

    it("rejects an example proof for another program vkey", async () => {
      const { bridge } = await deployBridge({ vkey: repeat(0x01) });
      const { proof, sp1PublicInputs } = EXAMPLE_PROOFS[0];
      await expect(bridge.update(proof, sp1PublicInputs)).to.be.revertedWithCustomError(bridge, "ProofVerificationFailed");
    });

    it("rejects replaying an applied example proof", async () => {
      const { bridge } = await deployBridge();
      const { proof, sp1PublicInputs, decoded } = EXAMPLE_PROOFS[0];
      await (await bridge.update(proof, sp1PublicInputs)).wait();
      await expect(bridge.update(proof, sp1PublicInputs))
        .to.be.revertedWithCustomError(bridge, "InputStoreHashMismatch")
        .withArgs(decoded.inputStoreHash, decoded.outputStoreHash);
    });

    it("rejects skipping an example proof", async () => {
      const { bridge } = await deployBridge();
      const { proof, sp1PublicInputs, decoded } = EXAMPLE_PROOFS[1];
      await expect(bridge.update(proof, sp1PublicInputs))
        .to.be.revertedWithCustomError(bridge, "InputStoreHashMismatch")
        .withArgs(decoded.inputStoreHash, INITIAL_STORE_HASH);
    });

    it("rejects an example proof anchored on another queue", async () => {
      const { bridge } = await deployBridge({ ethProofQueueAddress: "0x" + "05".repeat(20) });
      const { proof, sp1PublicInputs } = EXAMPLE_PROOFS[0];
      await expect(bridge.update(proof, sp1PublicInputs)).to.be.revertedWithCustomError(
        bridge,
        "ETHProofQueueAddressMismatch"
      );
    });

    it("rejects an example proof resuming from another queue cursor", async () => {
      const { bridge } = await deployBridge();
      await plantPackedState(await bridge.getAddress(), { queueCursor: 1n });
      const { proof, sp1PublicInputs } = EXAMPLE_PROOFS[0];
      await expect(bridge.update(proof, sp1PublicInputs))
        .to.be.revertedWithCustomError(bridge, "QueueCursorMismatch")
        .withArgs(0n, 1n);
    });

    it("rejects an example proof whose store hash does not chain", async () => {
      const { bridge } = await deployBridge({ latestHeliosStoreInputHash: repeat(0xee) });
      const { proof, sp1PublicInputs } = EXAMPLE_PROOFS[0];
      await expect(bridge.update(proof, sp1PublicInputs)).to.be.revertedWithCustomError(bridge, "InputStoreHashMismatch");
    });

    it("rejects an example proof whose head is not past the latest head", async () => {
      const { bridge } = await deployBridge();
      const { proof, sp1PublicInputs, decoded } = EXAMPLE_PROOFS[0];
      await plantPackedState(await bridge.getAddress(), { latestHead: decoded.outputSlot });
      await expect(bridge.update(proof, sp1PublicInputs))
        .to.be.revertedWithCustomError(bridge, "InvalidOutputSlot")
        .withArgs(decoded.outputSlot, decoded.outputSlot);
    });
  });

  describe("proof outputs", () => {
    it("decodes nori-bridge-head's ProofOutputs vectors", async () => {
      const { bridge } = await deployBridge();
      for (const vector of PROOF_OUTPUTS_VECTORS) {
        const decoded = await bridge.decodeProofOutputs(vector.bytes);
        expect(decoded.inputSlot, vector.name).to.equal(BigInt(vector.inputSlot));
        expect(decoded.inputStoreHash, vector.name).to.equal(vector.inputStoreHash);
        expect(decoded.outputSlot, vector.name).to.equal(BigInt(vector.outputSlot));
        expect(decoded.outputStoreHash, vector.name).to.equal(vector.outputStoreHash);
        expect(decoded.executionStateRoot, vector.name).to.equal(vector.executionStateRoot);
        expect(decoded.verifiedRequestsRoot, vector.name).to.equal(vector.verifiedRequestsRoot);
        expect(decoded.nextSyncCommitteeHash, vector.name).to.equal(vector.nextSyncCommitteeHash);
        expect(decoded.proofRequestQueueAddress, vector.name).to.equal(
          ethers.getAddress(vector.proofRequestQueueAddress)
        );
        expect(decoded.inputQueueCursor, vector.name).to.equal(BigInt(vector.inputQueueCursor));
        expect(decoded.outputQueueCursor, vector.name).to.equal(BigInt(vector.outputQueueCursor));
        expect(decoded.outputBlockNumber, vector.name).to.equal(BigInt(vector.outputBlockNumber));
      }
    });

    it("rejects public values other than PROOF_OUTPUTS_SIZE bytes", async () => {
      const { bridge } = await deployBridge();
      const extra = 24;
      const padded = `${PROOF_OUTPUTS_VECTORS[0].bytes}${"00".repeat(extra)}`;
      await expect(bridge.decodeProofOutputs(padded))
        .to.be.revertedWithCustomError(bridge, "DecodingProofFailed")
        .withArgs(PROOF_OUTPUTS_SIZE + extra);
    });
  });

  describe("proof queue batches", () => {
    async function deployWithBatches() {
      const fixture = await deployBridge();
      const batches = [
        { root: repeat(0xa0), inputQueueCursor: 0n, outputQueueCursor: 5n, outputBlockNumber: 100n },
        { root: repeat(0xa1), inputQueueCursor: 5n, outputQueueCursor: 9n, outputBlockNumber: 101n },
        { root: repeat(0xa2), inputQueueCursor: 9n, outputQueueCursor: 10n, outputBlockNumber: 102n },
      ];
      await plantProofQueueBatches(await fixture.bridge.getAddress(), batches);
      return { ...fixture, batches };
    }

    it("reads committed batches by index and in runs", async () => {
      const { bridge, batches } = await deployWithBatches();
      expect(await bridge.proofQueueBatchCount()).to.equal(3n);
      const second = await bridge.proofQueueBatch(1n);
      expect(second.root).to.equal(batches[1].root);
      expect(second.inputQueueCursor).to.equal(5n);
      expect(second.outputQueueCursor).to.equal(9n);
      expect(second.outputBlockNumber).to.equal(101n);
      const run = await bridge.proofQueueBatches(0n, 3n);
      expect(run.map((batch) => batch.root)).to.deep.equal(batches.map((batch) => batch.root));
    });

    it("finds the batch covering a request id", async () => {
      const { bridge } = await deployWithBatches();
      const expected: Array<[bigint, bigint]> = [
        [0n, 0n],
        [4n, 0n],
        [5n, 1n],
        [8n, 1n],
        [9n, 2n],
      ];
      for (const [requestId, index] of expected) {
        const [found] = await bridge.findProofQueueBatch(requestId);
        expect(found).to.equal(index);
      }
      await expect(bridge.findProofQueueBatch(10n))
        .to.be.revertedWithCustomError(bridge, "NoProofQueueBatchCovers")
        .withArgs(10n);
    });

    it("rejects reads beyond the committed batches", async () => {
      const { bridge } = await deployBridge();
      await expect(bridge.proofQueueBatch(0n)).to.be.revertedWithCustomError(bridge, "ProofQueueBatchNotCommitted");
      await expect(bridge.findProofQueueBatch(0n)).to.be.revertedWithCustomError(bridge, "NoProofQueueBatchCovers");
    });
  });

  describe("request leaves", () => {
    it("hashes each request as nori-bridge-head's vectors do", async () => {
      const { bridge } = await deployBridge();
      for (const vector of REQUEST_LEAF_VECTORS) {
        const request = {
          target: vector.target,
          collectionKeysCount: vector.collectionKeysCount,
          collectionKeys: vector.collectionKeys,
          value: BigInt(vector.value),
        };
        expect(await bridge.requestLeafHash(request), vector.name).to.equal(vector.leaf);
        expect(leafHash(request), vector.name).to.equal(vector.leaf);
      }
    });
  });

  describe("mint", () => {
    /** A batch of two deposits, for `recipient` and `other`, planted at index 0. */
    async function deployWithDeposits(lockedForRecipient = 1_500_000n) {
      const fixture = await deployBridge();
      const { bridge, recipient, other } = fixture;
      const deposit = (address: string, value: bigint): Request => ({
        target: TEST_ETH_TOKEN_BRIDGE_ADDRESS,
        collectionKeysCount: 1,
        collectionKeys: [ethers.sha256(address), ethers.ZeroHash],
        value,
      });
      const requests = [deposit(recipient.address, lockedForRecipient), deposit(other.address, 2_000_000n)];
      const leaves = requests.map(leafHash);
      const root = node(leaves[0], leaves[1]);
      await plantProofQueueBatches(await bridge.getAddress(), [
        { root, inputQueueCursor: 0n, outputQueueCursor: 2n, outputBlockNumber: 100n },
      ]);
      const witness = (index: number) => ({ path: [leaves[1 - index]], index: BigInt(index), value: requests[index] });
      return { ...fixture, requests, leaves, root, witness };
    }

    it("mints the locked amount of the TIP-20 to the committed recipient", async () => {
      const { bridge, token, recipient, root, witness } = await deployWithDeposits();
      await expect(bridge.connect(recipient).mint(witness(0), 0n))
        .to.emit(bridge, "MintApplied")
        .withArgs(recipient.address, root, 1_500_000n, 1_500_000n);
      expect(await token.balanceOf(recipient.address)).to.equal(1_500_000n);
      expect(await bridge.mintedSoFar(recipient.address)).to.equal(1_500_000n);
    });

    it("resolves both witnesses to the committed root", async () => {
      const { bridge, root, witness } = await deployWithDeposits();
      expect(await bridge.verifiedRequestWitnessRoot(witness(0))).to.equal(root);
      expect(await bridge.verifiedRequestWitnessRoot(witness(1))).to.equal(root);
    });

    it("mints nothing twice for the same deposit", async () => {
      const { bridge, recipient, witness } = await deployWithDeposits();
      await (await bridge.connect(recipient).mint(witness(0), 0n)).wait();
      await expect(bridge.connect(recipient).mint(witness(0), 0n)).to.be.revertedWithCustomError(bridge, "ZeroMintAmount");
    });

    it("mints only the newly locked amount after a later deposit", async () => {
      const { bridge, token, recipient, root, witness } = await deployWithDeposits();
      await (await bridge.connect(recipient).mint(witness(0), 0n)).wait();
      const more: Request = {
        target: TEST_ETH_TOKEN_BRIDGE_ADDRESS,
        collectionKeysCount: 1,
        collectionKeys: [ethers.sha256(recipient.address), ethers.ZeroHash],
        value: 2_500_000n,
      };
      const sibling = repeat(0x99);
      await plantProofQueueBatches(await bridge.getAddress(), [
        { root, inputQueueCursor: 0n, outputQueueCursor: 2n, outputBlockNumber: 100n },
        { root: node(leafHash(more), sibling), inputQueueCursor: 2n, outputQueueCursor: 4n, outputBlockNumber: 101n },
      ]);
      await (await bridge.connect(recipient).mint({ path: [sibling], index: 0n, value: more }, 1n)).wait();
      expect(await token.balanceOf(recipient.address)).to.equal(2_500_000n);
    });

    it("rejects a claim by anyone but the committed recipient", async () => {
      const { bridge, other, witness } = await deployWithDeposits();
      await expect(bridge.connect(other).mint(witness(0), 0n)).to.be.revertedWithCustomError(bridge, "CommitmentMismatch");
    });

    it("rejects a batch that is not committed", async () => {
      const { bridge, recipient, witness } = await deployWithDeposits();
      await expect(bridge.connect(recipient).mint(witness(0), 1n)).to.be.revertedWithCustomError(
        bridge,
        "ProofQueueBatchNotCommitted"
      );
    });

    it("rejects a witness against another batch's root", async () => {
      const { bridge, recipient, root, witness } = await deployWithDeposits();
      await plantProofQueueBatches(await bridge.getAddress(), [
        { root, inputQueueCursor: 0n, outputQueueCursor: 2n, outputBlockNumber: 100n },
        { root: repeat(0x77), inputQueueCursor: 2n, outputQueueCursor: 3n, outputBlockNumber: 101n },
      ]);
      await expect(bridge.connect(recipient).mint(witness(0), 1n)).to.be.revertedWithCustomError(
        bridge,
        "ProofQueueBatchRootMismatch"
      );
    });

    it("rejects a witness index outside the batch", async () => {
      const { bridge, recipient, requests } = await deployWithDeposits();
      const leaves = [repeat(0xa0), repeat(0xa1), leafHash(requests[0]), repeat(0xa3)];
      const root = node(node(leaves[0], leaves[1]), node(leaves[2], leaves[3]));
      await plantProofQueueBatches(await bridge.getAddress(), [
        { root, inputQueueCursor: 0n, outputQueueCursor: 2n, outputBlockNumber: 100n },
      ]);
      const witness = { path: [leaves[3], node(leaves[0], leaves[1])], index: 2n, value: requests[0] };
      await expect(bridge.connect(recipient).mint(witness, 0n))
        .to.be.revertedWithCustomError(bridge, "WitnessIndexOutsideProofQueueBatch")
        .withArgs(2n, 2n);
    });

    it("rejects a deposit of another contract", async () => {
      const { bridge, recipient } = await deployBridge();
      const foreign: Request = {
        target: "0x" + "33".repeat(20),
        collectionKeysCount: 1,
        collectionKeys: [ethers.sha256(recipient.address), ethers.ZeroHash],
        value: 1_000_000n,
      };
      const sibling = repeat(0x99);
      await plantProofQueueBatches(await bridge.getAddress(), [
        { root: node(leafHash(foreign), sibling), inputQueueCursor: 0n, outputQueueCursor: 2n, outputBlockNumber: 100n },
      ]);
      await expect(
        bridge.connect(recipient).mint({ path: [sibling], index: 0n, value: foreign }, 0n)
      ).to.be.revertedWithCustomError(bridge, "NotTokenBridgeRequest");
    });

    it("rejects a locked amount beyond 64 bits", async () => {
      const { bridge, recipient } = await deployBridge();
      const huge: Request = {
        target: TEST_ETH_TOKEN_BRIDGE_ADDRESS,
        collectionKeysCount: 1,
        collectionKeys: [ethers.sha256(recipient.address), ethers.ZeroHash],
        value: MAX_U64 + 1n,
      };
      const sibling = repeat(0x99);
      await plantProofQueueBatches(await bridge.getAddress(), [
        { root: node(leafHash(huge), sibling), inputQueueCursor: 0n, outputQueueCursor: 2n, outputBlockNumber: 100n },
      ]);
      await expect(
        bridge.connect(recipient).mint({ path: [sibling], index: 0n, value: huge }, 0n)
      ).to.be.revertedWithCustomError(bridge, "LockedAmountOverflow");
    });

    it("rejects a malformed witness", async () => {
      const { bridge, recipient, witness } = await deployWithDeposits();
      const tooDeep = { ...witness(0), path: Array(MAX_TREE_DEPTH + 1).fill(repeat(0x01)) };
      await expect(bridge.connect(recipient).mint(tooDeep, 0n)).to.be.revertedWithCustomError(
        bridge,
        "InvalidDepositWitness"
      );
      const tooManyKeys = {
        ...witness(0),
        value: { ...witness(0).value, collectionKeysCount: MAX_COLLECTION_KEYS + 1 },
      };
      await expect(bridge.connect(recipient).mint(tooManyKeys, 0n)).to.be.revertedWithCustomError(
        bridge,
        "InvalidDepositWitness"
      );
    });
  });

  describe("ERC-20 mirrors", () => {
    /** An Ethereum ERC-20 the mirror stands for; on Tempo it is only a key. */
    const ETH_TOKEN = "0x" + "44".repeat(20);
    const tokenKey = (address: string) => ethers.zeroPadValue(address, 32);

    /** A bridge with a mirror of `ETH_TOKEN` registered by its deployer. */
    async function deployWithMirror() {
      const fixture = await deployBridge();
      const { bridge } = fixture;
      await (await bridge.registerMirror(ETH_TOKEN, "Nori USDC", "nUSDC", "USD", ethers.hexlify(randomBytes(32)))).wait();
      const mirror = ITIP20__factory.connect(await bridge.mirrorOf(ETH_TOKEN), fixture.deployer);
      return { ...fixture, mirror };
    }

    /** Plants batches each holding one request, at indices from 0, and returns each request's witness. */
    async function plantOneRequestBatches(bridgeAddress: string, requests: Request[]) {
      const sibling = repeat(0x99);
      await plantProofQueueBatches(
        bridgeAddress,
        requests.map((request, i) => ({
          root: node(leafHash(request), sibling),
          inputQueueCursor: BigInt(2 * i),
          outputQueueCursor: BigInt(2 * i + 2),
          outputBlockNumber: BigInt(100 + i),
        }))
      );
      return requests.map((value) => ({ path: [sibling], index: 0n, value }));
    }

    const erc20Deposit = (recipient: string, ethToken: string, value: bigint): Request => ({
      target: TEST_ETH_TOKEN_BRIDGE_ADDRESS,
      collectionKeysCount: 2,
      collectionKeys: [ethers.sha256(recipient), tokenKey(ethToken)],
      value,
    });

    const pauseState = (ethToken: string, value: bigint): Request => ({
      target: TEST_ETH_TOKEN_BRIDGE_ADDRESS,
      collectionKeysCount: 2,
      collectionKeys: [PAUSE_KEY, tokenKey(ethToken)],
      value,
    });

    it("keeps PAUSE_KEY and the pause states in step with the contract", async () => {
      const { bridge } = await deployBridge();
      expect(await bridge.PAUSE_KEY()).to.equal(PAUSE_KEY);
      expect(await bridge.PAUSE_STATE_UNPAUSED()).to.equal(PAUSE_STATE_UNPAUSED);
      expect(await bridge.PAUSE_STATE_PAUSED()).to.equal(PAUSE_STATE_PAUSED);
    });

    it("registers one 6-decimal TIP-20 mirror per ERC-20", async () => {
      const { bridge } = await deployBridge();
      await expect(bridge.registerMirror(ETH_TOKEN, "Nori USDC", "nUSDC", "USD", ethers.hexlify(randomBytes(32)))).to.emit(
        bridge,
        "MirrorRegistered"
      );
      const mirror = ITIP20__factory.connect(await bridge.mirrorOf(ETH_TOKEN), ethers.provider);
      expect(await mirror.decimals()).to.equal(TIP20_DECIMALS);
      expect(await mirror.paused()).to.equal(false);
      await expect(
        bridge.registerMirror(ETH_TOKEN, "Nori USDC", "nUSDC", "USD", ethers.hexlify(randomBytes(32)))
      ).to.be.revertedWithCustomError(bridge, "MirrorExists");
    });

    it("rejects registering by anyone but the deployer", async () => {
      const { bridge, other, deployer } = await deployBridge();
      await expect(
        bridge.connect(other).registerMirror(ETH_TOKEN, "Nori USDC", "nUSDC", "USD", ethers.hexlify(randomBytes(32)))
      )
        .to.be.revertedWithCustomError(bridge, "NotMirrorAdmin")
        .withArgs(other.address, deployer.address);
    });

    it("mints the mirror against a proven ERC-20 deposit, only the new amount each time", async () => {
      const { bridge, mirror, recipient } = await deployWithMirror();
      const [first, second] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, ETH_TOKEN, 1_500_000n),
        erc20Deposit(recipient.address, ETH_TOKEN, 2_500_000n),
      ]);
      await expect(bridge.connect(recipient).mintERC20(first, 0n)).to.emit(bridge, "ERC20MintApplied");
      expect(await mirror.balanceOf(recipient.address)).to.equal(1_500_000n);
      await expect(bridge.connect(recipient).mintERC20(first, 0n)).to.be.revertedWithCustomError(bridge, "ZeroMintAmount");
      await (await bridge.connect(recipient).mintERC20(second, 1n)).wait();
      expect(await mirror.balanceOf(recipient.address)).to.equal(2_500_000n);
      expect(await bridge.erc20MintedSoFar(ETH_TOKEN, recipient.address)).to.equal(2_500_000n);
    });

    it("rejects an ERC-20 deposit for a claim by anyone but the committed recipient", async () => {
      const { bridge, recipient, other } = await deployWithMirror();
      const [witness] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
      ]);
      await expect(bridge.connect(other).mintERC20(witness, 0n)).to.be.revertedWithCustomError(bridge, "CommitmentMismatch");
    });

    it("rejects an ERC-20 deposit of a token with no mirror", async () => {
      const { bridge, recipient } = await deployWithMirror();
      const unmirrored = "0x" + "55".repeat(20);
      const [witness] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, unmirrored, 1_000_000n),
      ]);
      await expect(bridge.connect(recipient).mintERC20(witness, 0n))
        .to.be.revertedWithCustomError(bridge, "NoMirror")
        .withArgs(ethers.getAddress(unmirrored));
    });

    it("rejects an ERC-20 deposit as an ETH mint, and an ETH deposit as an ERC-20 mint", async () => {
      const { bridge, recipient } = await deployWithMirror();
      const ethDeposit: Request = {
        target: TEST_ETH_TOKEN_BRIDGE_ADDRESS,
        collectionKeysCount: 1,
        collectionKeys: [ethers.sha256(recipient.address), ethers.ZeroHash],
        value: 1_000_000n,
      };
      const [erc20Witness, ethWitness] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
        ethDeposit,
      ]);
      await expect(bridge.connect(recipient).mint(erc20Witness, 0n))
        .to.be.revertedWithCustomError(bridge, "CollectionKeysCountMismatch")
        .withArgs(2, 1);
      await expect(bridge.connect(recipient).mintERC20(ethWitness, 1n))
        .to.be.revertedWithCustomError(bridge, "CollectionKeysCountMismatch")
        .withArgs(1, 2);
    });

    it("rejects a token key wider than an address", async () => {
      const { bridge, recipient } = await deployWithMirror();
      const wide: Request = {
        ...erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
        collectionKeys: [ethers.sha256(recipient.address), repeat(0x44)],
      };
      const [witness] = await plantOneRequestBatches(await bridge.getAddress(), [wide]);
      await expect(bridge.connect(recipient).mintERC20(witness, 0n)).to.be.revertedWithCustomError(bridge, "InvalidTokenKey");
    });

    it("pauses and unpauses the mirror as the proven pause state changes", async () => {
      const { bridge, mirror } = await deployWithMirror();
      const [paused, unpaused] = await plantOneRequestBatches(await bridge.getAddress(), [
        pauseState(ETH_TOKEN, PAUSE_STATE_PAUSED),
        pauseState(ETH_TOKEN, PAUSE_STATE_UNPAUSED),
      ]);
      expect([...(await bridge.lastPauseApplied(ETH_TOKEN))]).to.deep.equal([false, 0n]);

      await expect(bridge.applyPause(paused, 0n))
        .to.emit(bridge, "PauseApplied")
        .withArgs(ethers.getAddress(ETH_TOKEN), await mirror.getAddress(), true, 0n);
      expect(await mirror.paused()).to.equal(true);
      expect([...(await bridge.lastPauseApplied(ETH_TOKEN))]).to.deep.equal([true, 0n]);

      await (await bridge.applyPause(unpaused, 1n)).wait();
      expect(await mirror.paused()).to.equal(false);
    });

    it("keeps a paused mirror's holders from moving it", async () => {
      const { bridge, mirror, recipient, other } = await deployWithMirror();
      const [deposit, paused] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
        pauseState(ETH_TOKEN, PAUSE_STATE_PAUSED),
      ]);
      await (await bridge.connect(recipient).mintERC20(deposit, 0n)).wait();
      await (await bridge.applyPause(paused, 1n)).wait();
      const transfer = new ethers.Contract(
        await mirror.getAddress(),
        ["function transfer(address to, uint256 amount) returns (bool)"],
        recipient
      );
      await expect(transfer.transfer(other.address, 1n)).to.be.revert(ethers);
      expect(await mirror.balanceOf(other.address)).to.equal(0n);
    });

    it("rejects a pause state from a batch no newer than the last one applied", async () => {
      const { bridge } = await deployWithMirror();
      const [older, newer] = await plantOneRequestBatches(await bridge.getAddress(), [
        pauseState(ETH_TOKEN, PAUSE_STATE_UNPAUSED),
        pauseState(ETH_TOKEN, PAUSE_STATE_PAUSED),
      ]);
      await (await bridge.applyPause(newer, 1n)).wait();
      await expect(bridge.applyPause(older, 0n)).to.be.revertedWithCustomError(bridge, "PauseNotNewer").withArgs(0n, 1n);
      await expect(bridge.applyPause(newer, 1n)).to.be.revertedWithCustomError(bridge, "PauseNotNewer").withArgs(1n, 1n);
    });

    it("rejects an ERC-20 deposit as a pause state, and a pause state other than paused or unpaused", async () => {
      const { bridge, recipient } = await deployWithMirror();
      const [deposit, neither] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, ETH_TOKEN, PAUSE_STATE_PAUSED),
        pauseState(ETH_TOKEN, 3n),
      ]);
      await expect(bridge.applyPause(deposit, 0n)).to.be.revertedWithCustomError(bridge, "NotPauseState");
      await expect(bridge.applyPause(neither, 1n))
        .to.be.revertedWithCustomError(bridge, "InvalidPauseState")
        .withArgs(3n);
    });

    it("counts every mirror unit it mints, across recipients", async () => {
      const { bridge, mirror, recipient, other } = await deployWithMirror();
      const [mine, theirs] = await plantOneRequestBatches(await bridge.getAddress(), [
        erc20Deposit(recipient.address, ETH_TOKEN, 1_500_000n),
        erc20Deposit(other.address, ETH_TOKEN, 700_000n),
      ]);
      await (await bridge.connect(recipient).mintERC20(mine, 0n)).wait();
      await (await bridge.connect(other).mintERC20(theirs, 1n)).wait();
      expect(await bridge.erc20TotalMinted(ETH_TOKEN)).to.equal(2_200_000n);
      expect(await mirror.totalSupply()).to.equal(2_200_000n);
      expect(await bridge.ethTokenOf(await mirror.getAddress())).to.equal(ethers.getAddress(ETH_TOKEN));
    });

    describe("an issuer's own TIP-20 (adoptMirror)", () => {
      const PAUSE_ROLE = ethers.id(PAUSE_ROLE_NAME);
      const UNPAUSE_ROLE = ethers.id(UNPAUSE_ROLE_NAME);
      const DEFAULT_ADMIN_ROLE = ethers.ZeroHash;

      /**
       * The issuer's TIP-20, created through TIP20Factory with the issuer as
       * its admin, and the roles it grants the bridge.
       */
      async function issuerTip20(
        bridgeAddress: string,
        issuer: Awaited<ReturnType<typeof deployBridge>>["other"],
        roles: string[] = [ISSUER_ROLE, PAUSE_ROLE, UNPAUSE_ROLE]
      ) {
        const factory = ITIP20Factory__factory.connect(TIP20_FACTORY_ADDRESS, issuer);
        const args = ["Issuer USD", "iUSD", "USD", PATH_USD_ADDRESS, issuer.address, ethers.hexlify(randomBytes(32))] as const;
        const address = await factory.createToken.staticCall(...args);
        await (await factory.createToken(...args)).wait();
        const tip20 = ITIP20__factory.connect(address, issuer);
        for (const role of roles) await (await tip20.grantRole(role, bridgeAddress)).wait();
        return tip20;
      }

      /** A bridge that adopted the issuer's TIP-20 as the mirror of `ETH_TOKEN`; `other` is the issuer. */
      async function deployWithAdoptedMirror() {
        const fixture = await deployBridge();
        const { bridge, other: issuer } = fixture;
        const mirror = await issuerTip20(await bridge.getAddress(), issuer);
        await (await bridge.adoptMirror(ETH_TOKEN, await mirror.getAddress())).wait();
        return { ...fixture, issuer, mirror };
      }

      it("adopts it, and the issuer stays its admin", async () => {
        const { bridge, other: issuer, deployer } = await deployBridge();
        const tip20 = await issuerTip20(await bridge.getAddress(), issuer);
        await expect(bridge.adoptMirror(ETH_TOKEN, await tip20.getAddress()))
          .to.emit(bridge, "MirrorAdopted")
          .withArgs(ethers.getAddress(ETH_TOKEN), await tip20.getAddress());
        expect(await bridge.mirrorOf(ETH_TOKEN)).to.equal(await tip20.getAddress());
        expect(await bridge.ethTokenOf(await tip20.getAddress())).to.equal(ethers.getAddress(ETH_TOKEN));
        expect(await tip20.hasRole(issuer.address, DEFAULT_ADMIN_ROLE)).to.equal(true);
        expect(await tip20.hasRole(await bridge.getAddress(), DEFAULT_ADMIN_ROLE)).to.equal(false);
        expect(await tip20.hasRole(deployer.address, DEFAULT_ADMIN_ROLE)).to.equal(false);
      });

      it("rejects adopting by anyone but the deployer", async () => {
        const { bridge, other: issuer, deployer } = await deployBridge();
        const tip20 = await issuerTip20(await bridge.getAddress(), issuer);
        await expect(bridge.connect(issuer).adoptMirror(ETH_TOKEN, await tip20.getAddress()))
          .to.be.revertedWithCustomError(bridge, "NotMirrorAdmin")
          .withArgs(issuer.address, deployer.address);
      });

      for (const [name, missing] of [
        ["ISSUER_ROLE", ISSUER_ROLE_NAME],
        ["PAUSE_ROLE", PAUSE_ROLE_NAME],
        ["UNPAUSE_ROLE", UNPAUSE_ROLE_NAME],
      ] as const) {
        it(`rejects a TIP-20 that did not grant the bridge ${name}`, async () => {
          const { bridge, other: issuer } = await deployBridge();
          const roles = [ISSUER_ROLE, PAUSE_ROLE, UNPAUSE_ROLE].filter((role) => role !== ethers.id(missing));
          const tip20 = await issuerTip20(await bridge.getAddress(), issuer, roles);
          await expect(bridge.adoptMirror(ETH_TOKEN, await tip20.getAddress()))
            .to.be.revertedWithCustomError(bridge, "MissingMirrorRole")
            .withArgs(await tip20.getAddress(), ethers.id(missing));
        });
      }

      it("rejects an address that is not a TIP-20, and the bridged nETH", async () => {
        const { bridge, token } = await deployBridge();
        const notTip20 = "0x" + "66".repeat(20);
        await expect(bridge.adoptMirror(ETH_TOKEN, notTip20))
          .to.be.revertedWithCustomError(bridge, "NotTIP20")
          .withArgs(ethers.getAddress(notTip20));
        await expect(bridge.adoptMirror(ETH_TOKEN, await token.getAddress()))
          .to.be.revertedWithCustomError(bridge, "NotTIP20")
          .withArgs(await token.getAddress());
      });

      it("rejects a second mirror of one ERC-20, and one TIP-20 mirroring two ERC-20s", async () => {
        const { bridge, mirror, issuer } = await deployWithAdoptedMirror();
        const another = await issuerTip20(await bridge.getAddress(), issuer);
        await expect(bridge.adoptMirror(ETH_TOKEN, await another.getAddress())).to.be.revertedWithCustomError(
          bridge,
          "MirrorExists"
        );
        await expect(bridge.registerMirror(ETH_TOKEN, "Again", "AGN", "USD", ethers.hexlify(randomBytes(32)))).to.be.revertedWithCustomError(
          bridge,
          "MirrorExists"
        );
        await expect(bridge.adoptMirror("0x" + "55".repeat(20), await mirror.getAddress()))
          .to.be.revertedWithCustomError(bridge, "AlreadyAMirror")
          .withArgs(await mirror.getAddress(), ethers.getAddress(ETH_TOKEN));
      });

      it("mints it against proven deposits and follows the ERC-20's pause, as a created mirror does", async () => {
        const { bridge, mirror, recipient } = await deployWithAdoptedMirror();
        const [deposit, paused, unpaused] = await plantOneRequestBatches(await bridge.getAddress(), [
          erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
          pauseState(ETH_TOKEN, PAUSE_STATE_PAUSED),
          pauseState(ETH_TOKEN, PAUSE_STATE_UNPAUSED),
        ]);
        await expect(bridge.connect(recipient).mintERC20(deposit, 0n)).to.emit(bridge, "ERC20MintApplied");
        expect(await mirror.balanceOf(recipient.address)).to.equal(1_000_000n);
        expect(await bridge.erc20TotalMinted(ETH_TOKEN)).to.equal(1_000_000n);
        await (await bridge.applyPause(paused, 1n)).wait();
        expect(await mirror.paused()).to.equal(true);
        await (await bridge.applyPause(unpaused, 2n)).wait();
        expect(await mirror.paused()).to.equal(false);
      });

      it("leaves a mint the issuer's supply cap refuses to be claimed once the cap allows it", async () => {
        const { bridge, mirror, issuer, recipient } = await deployWithAdoptedMirror();
        const capped = new ethers.Contract(
          await mirror.getAddress(),
          ["function setSupplyCap(uint256 newSupplyCap)"],
          issuer
        );
        await (await capped.setSupplyCap(500_000n)).wait();
        const [deposit] = await plantOneRequestBatches(await bridge.getAddress(), [
          erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
        ]);
        await expect(bridge.connect(recipient).mintERC20(deposit, 0n)).to.be.revert(ethers);
        expect(await bridge.erc20MintedSoFar(ETH_TOKEN, recipient.address)).to.equal(0n);
        await (await capped.setSupplyCap(1_000_000n)).wait();
        await (await bridge.connect(recipient).mintERC20(deposit, 0n)).wait();
        expect(await mirror.balanceOf(recipient.address)).to.equal(1_000_000n);
      });

      it("stops minting once the issuer revokes the bridge's ISSUER_ROLE", async () => {
        const { bridge, mirror, issuer, recipient } = await deployWithAdoptedMirror();
        const revoke = new ethers.Contract(
          await mirror.getAddress(),
          ["function revokeRole(bytes32 role, address account)"],
          issuer
        );
        await (await revoke.revokeRole(ISSUER_ROLE, await bridge.getAddress())).wait();
        const [deposit] = await plantOneRequestBatches(await bridge.getAddress(), [
          erc20Deposit(recipient.address, ETH_TOKEN, 1_000_000n),
        ]);
        await expect(bridge.connect(recipient).mintERC20(deposit, 0n)).to.be.revert(ethers);
        expect(await mirror.totalSupply()).to.equal(0n);
      });
    });
  });
});
