// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IFeeManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IFeeManager";
  readonly sourceName: "contracts/interfaces/IFeeManager.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"user","type":"address"}],"name":"userTokens","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IFeeManager.sol";
  readonly buildInfoId: "solc-0_8_28-e9674a2cc46a0743bd7c39f3da8bfea080a60359";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IFeeManager"]: IFeeManager$Type;
    ["contracts/interfaces/IFeeManager.sol:IFeeManager"]: IFeeManager$Type;
  }
}