[workspace]
members = [
    "cli",
    "nori-hash-utils",
    "proof-submitter",
    "test-utils",
]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.89.0"

[workspace.dependencies]
# workspace crates
proof-submitter = { path = "proof-submitter" }
test-utils = { path = "test-utils" }

# nori
nori-elf = { git = "https://github.com/Nori-zk/nori-bridge-head", branch = "FEAT/tempo-bridge-sepolia-glamsterdam" }
nori-hash = { git = "https://github.com/Nori-zk/nori-bridge-head", branch = "FEAT/tempo-bridge-sepolia-glamsterdam", default-features = false }
nori-sp1-helios-primitives = { git = "https://github.com/Nori-zk/nori-bridge-head", branch = "FEAT/tempo-bridge-sepolia-glamsterdam", default-features = false }

# general
alloy = { version = "1.6", default-features = false }
alloy-primitives = "1.7.1"
base64 = "0.22"
bytemuck = "1"
dotenvy = "0.15"
serde_json = "1"
tokio = "1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
