[package]
name = "proof-submitter"
version = "0.0.1"
edition.workspace = true
rust-version.workspace = true

[dependencies]
nori-sp1-helios-primitives = { workspace = true }
alloy = { workspace = true, features = [
    "contract",
    "network",
    "providers",
    "reqwest",
    "rpc-types",
    "signer-local",
    "sol-types",
] }
alloy-primitives = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
thiserror = "2"
dotenvy = { workspace = true }
log = "0.4"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
nori-elf = { workspace = true }
test-utils = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
