/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface NoriTokenBridgeInterface extends Interface {
    getFunction(nameOrSignature: "DECIMALS" | "FEE_DENOMINATOR" | "MAX_FEE_RATE" | "MAX_MAGNITUDE" | "MIN_FEE_BU" | "MIN_LOCK_AMOUNT_WEI" | "PAUSE_KEY" | "PAUSE_STATE_PAUSED" | "PAUSE_STATE_UNPAUSED" | "WEI_PER_BRIDGE_UNIT" | "accumulatedFees" | "accumulatedTokenFees" | "bridgeOperator" | "calcGrossLockAmount" | "feeRecipient" | "lockERC20" | "lockFeeRate" | "lockTokens" | "lockedERC20" | "lockedTokens" | "pauseState" | "previewLock" | "previewLockERC20" | "proofQueue" | "setBridgeOperator" | "setFeeRecipient" | "setLockFeeRate" | "syncPause" | "totalLockedBU" | "totalLockedERC20BU" | "unlockTokens" | "withdrawFees" | "withdrawTokenFees"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BridgeOperatorSet" | "ERC20Locked" | "FeeRecipientSet" | "FeesWithdrawn" | "LockFeeRateSet" | "PauseSynced" | "TokenFeesWithdrawn" | "TokensLocked"): EventFragment;

    encodeFunctionData(functionFragment: 'DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'FEE_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_FEE_RATE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_MAGNITUDE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_FEE_BU', values?: undefined): string;
encodeFunctionData(functionFragment: 'MIN_LOCK_AMOUNT_WEI', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_KEY', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_STATE_PAUSED', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_STATE_UNPAUSED', values?: undefined): string;
encodeFunctionData(functionFragment: 'WEI_PER_BRIDGE_UNIT', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'accumulatedTokenFees', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'bridgeOperator', values?: undefined): string;
encodeFunctionData(functionFragment: 'calcGrossLockAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'feeRecipient', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockERC20', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockFeeRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'lockTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedERC20', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedTokens', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pauseState', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'previewLock', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'previewLockERC20', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'proofQueue', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBridgeOperator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setFeeRecipient', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setLockFeeRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'syncPause', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalLockedBU', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalLockedERC20BU', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unlockTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawFees', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawTokenFees', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'FEE_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_FEE_RATE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_MAGNITUDE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_FEE_BU', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MIN_LOCK_AMOUNT_WEI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_KEY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_STATE_PAUSED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_STATE_UNPAUSED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WEI_PER_BRIDGE_UNIT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accumulatedTokenFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bridgeOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calcGrossLockAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockERC20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockFeeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedERC20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseState', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewLock', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewLockERC20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofQueue', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBridgeOperator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setFeeRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLockFeeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'syncPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLockedBU', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalLockedERC20BU', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unlockTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawTokenFees', data: BytesLike): Result;
  }

  
    export namespace BridgeOperatorSetEvent {
      export type InputTuple = [oldOperator: AddressLike, newOperator: AddressLike];
      export type OutputTuple = [oldOperator: string, newOperator: string];
      export interface OutputObject {oldOperator: string, newOperator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ERC20LockedEvent {
      export type InputTuple = [user: AddressLike, token: AddressLike, codeChallenge: BigNumberish, amount: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [user: string, token: string, codeChallenge: bigint, amount: bigint, fee: bigint];
      export interface OutputObject {user: string, token: string, codeChallenge: bigint, amount: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeeRecipientSetEvent {
      export type InputTuple = [oldRecipient: AddressLike, newRecipient: AddressLike];
      export type OutputTuple = [oldRecipient: string, newRecipient: string];
      export interface OutputObject {oldRecipient: string, newRecipient: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FeesWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [recipient: string, amount: bigint];
      export interface OutputObject {recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LockFeeRateSetEvent {
      export type InputTuple = [oldRate: BigNumberish, newRate: BigNumberish];
      export type OutputTuple = [oldRate: bigint, newRate: bigint];
      export interface OutputObject {oldRate: bigint, newRate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PauseSyncedEvent {
      export type InputTuple = [token: AddressLike, paused: boolean];
      export type OutputTuple = [token: string, paused: boolean];
      export interface OutputObject {token: string, paused: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenFeesWithdrawnEvent {
      export type InputTuple = [recipient: AddressLike, token: AddressLike, amount: BigNumberish];
      export type OutputTuple = [recipient: string, token: string, amount: bigint];
      export interface OutputObject {recipient: string, token: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensLockedEvent {
      export type InputTuple = [user: AddressLike, codeChallenge: BigNumberish, amount: BigNumberish, fee: BigNumberish];
      export type OutputTuple = [user: string, codeChallenge: bigint, amount: bigint, fee: bigint];
      export interface OutputObject {user: string, codeChallenge: bigint, amount: bigint, fee: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoriTokenBridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoriTokenBridge;
    waitForDeployment(): Promise<this>;

    interface: NoriTokenBridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    FEE_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_FEE_RATE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_MAGNITUDE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_FEE_BU: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MIN_LOCK_AMOUNT_WEI: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAUSE_KEY: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_STATE_PAUSED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAUSE_STATE_UNPAUSED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WEI_PER_BRIDGE_UNIT: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedFees: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accumulatedTokenFees: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    bridgeOperator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    calcGrossLockAmount: TypedContractMethod<
      [desiredNetAmount: BigNumberish, ],
      [[bigint, bigint, bigint] & {grossAmount: bigint, fee: bigint, actualNetAmount: bigint }],
      'view'
    >
    

    
    feeRecipient: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lockERC20: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, codeChallenge: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    lockFeeRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lockTokens: TypedContractMethod<
      [codeChallenge: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    lockedERC20: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    lockedTokens: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    pauseState: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    previewLock: TypedContractMethod<
      [grossAmount: BigNumberish, ],
      [[bigint, bigint] & {feeWei: bigint, netWei: bigint }],
      'view'
    >
    

    
    previewLockERC20: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [[bigint, bigint, bigint] & {queueFeeWei: bigint, fee: bigint, net: bigint }],
      'view'
    >
    

    
    proofQueue: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setBridgeOperator: TypedContractMethod<
      [newOperator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setFeeRecipient: TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setLockFeeRate: TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    syncPause: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'payable'
    >
    

    
    totalLockedBU: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalLockedERC20BU: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    unlockTokens: TypedContractMethod<
      [],
      [void],
      'view'
    >
    

    
    withdrawFees: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawTokenFees: TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'FEE_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_FEE_RATE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_MAGNITUDE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_FEE_BU'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MIN_LOCK_AMOUNT_WEI'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_KEY'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_STATE_PAUSED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_STATE_UNPAUSED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WEI_PER_BRIDGE_UNIT'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedFees'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accumulatedTokenFees'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'bridgeOperator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'calcGrossLockAmount'): TypedContractMethod<
      [desiredNetAmount: BigNumberish, ],
      [[bigint, bigint, bigint] & {grossAmount: bigint, fee: bigint, actualNetAmount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'feeRecipient'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lockERC20'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, codeChallenge: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'lockFeeRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockTokens'): TypedContractMethod<
      [codeChallenge: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'lockedERC20'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lockedTokens'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pauseState'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'previewLock'): TypedContractMethod<
      [grossAmount: BigNumberish, ],
      [[bigint, bigint] & {feeWei: bigint, netWei: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'previewLockERC20'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [[bigint, bigint, bigint] & {queueFeeWei: bigint, fee: bigint, net: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'proofQueue'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setBridgeOperator'): TypedContractMethod<
      [newOperator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setFeeRecipient'): TypedContractMethod<
      [newRecipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setLockFeeRate'): TypedContractMethod<
      [newRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'syncPause'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'totalLockedBU'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalLockedERC20BU'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'unlockTokens'): TypedContractMethod<
      [],
      [void],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawFees'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawTokenFees'): TypedContractMethod<
      [token: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BridgeOperatorSet'): TypedContractEvent<BridgeOperatorSetEvent.InputTuple, BridgeOperatorSetEvent.OutputTuple, BridgeOperatorSetEvent.OutputObject>;
getEvent(key: 'ERC20Locked'): TypedContractEvent<ERC20LockedEvent.InputTuple, ERC20LockedEvent.OutputTuple, ERC20LockedEvent.OutputObject>;
getEvent(key: 'FeeRecipientSet'): TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
getEvent(key: 'FeesWithdrawn'): TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
getEvent(key: 'LockFeeRateSet'): TypedContractEvent<LockFeeRateSetEvent.InputTuple, LockFeeRateSetEvent.OutputTuple, LockFeeRateSetEvent.OutputObject>;
getEvent(key: 'PauseSynced'): TypedContractEvent<PauseSyncedEvent.InputTuple, PauseSyncedEvent.OutputTuple, PauseSyncedEvent.OutputObject>;
getEvent(key: 'TokenFeesWithdrawn'): TypedContractEvent<TokenFeesWithdrawnEvent.InputTuple, TokenFeesWithdrawnEvent.OutputTuple, TokenFeesWithdrawnEvent.OutputObject>;
getEvent(key: 'TokensLocked'): TypedContractEvent<TokensLockedEvent.InputTuple, TokensLockedEvent.OutputTuple, TokensLockedEvent.OutputObject>;

    filters: {
      
      'BridgeOperatorSet(address,address)': TypedContractEvent<BridgeOperatorSetEvent.InputTuple, BridgeOperatorSetEvent.OutputTuple, BridgeOperatorSetEvent.OutputObject>;
      BridgeOperatorSet: TypedContractEvent<BridgeOperatorSetEvent.InputTuple, BridgeOperatorSetEvent.OutputTuple, BridgeOperatorSetEvent.OutputObject>;
    

      'ERC20Locked(address,address,uint256,uint256,uint256)': TypedContractEvent<ERC20LockedEvent.InputTuple, ERC20LockedEvent.OutputTuple, ERC20LockedEvent.OutputObject>;
      ERC20Locked: TypedContractEvent<ERC20LockedEvent.InputTuple, ERC20LockedEvent.OutputTuple, ERC20LockedEvent.OutputObject>;
    

      'FeeRecipientSet(address,address)': TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
      FeeRecipientSet: TypedContractEvent<FeeRecipientSetEvent.InputTuple, FeeRecipientSetEvent.OutputTuple, FeeRecipientSetEvent.OutputObject>;
    

      'FeesWithdrawn(address,uint256)': TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
      FeesWithdrawn: TypedContractEvent<FeesWithdrawnEvent.InputTuple, FeesWithdrawnEvent.OutputTuple, FeesWithdrawnEvent.OutputObject>;
    

      'LockFeeRateSet(uint16,uint16)': TypedContractEvent<LockFeeRateSetEvent.InputTuple, LockFeeRateSetEvent.OutputTuple, LockFeeRateSetEvent.OutputObject>;
      LockFeeRateSet: TypedContractEvent<LockFeeRateSetEvent.InputTuple, LockFeeRateSetEvent.OutputTuple, LockFeeRateSetEvent.OutputObject>;
    

      'PauseSynced(address,bool)': TypedContractEvent<PauseSyncedEvent.InputTuple, PauseSyncedEvent.OutputTuple, PauseSyncedEvent.OutputObject>;
      PauseSynced: TypedContractEvent<PauseSyncedEvent.InputTuple, PauseSyncedEvent.OutputTuple, PauseSyncedEvent.OutputObject>;
    

      'TokenFeesWithdrawn(address,address,uint256)': TypedContractEvent<TokenFeesWithdrawnEvent.InputTuple, TokenFeesWithdrawnEvent.OutputTuple, TokenFeesWithdrawnEvent.OutputObject>;
      TokenFeesWithdrawn: TypedContractEvent<TokenFeesWithdrawnEvent.InputTuple, TokenFeesWithdrawnEvent.OutputTuple, TokenFeesWithdrawnEvent.OutputObject>;
    

      'TokensLocked(address,uint256,uint256,uint256)': TypedContractEvent<TokensLockedEvent.InputTuple, TokensLockedEvent.OutputTuple, TokensLockedEvent.OutputObject>;
      TokensLocked: TypedContractEvent<TokensLockedEvent.InputTuple, TokensLockedEvent.OutputTuple, TokensLockedEvent.OutputObject>;
    
    };
  }