import type { NoriSP1ProofInput } from '@nori-zk/pts-types';
import {
    decodeConsensusMptProof,
    sp1Groth16ProofBytes,
    sp1ProgramVkey,
    sp1PublicValues,
} from './utils.js';
import { bridgeHeadNoriSP1HeliosProgramVk } from './integrity/BridgeHead.NoriSP1HeliosProgram.vk.js';
import { proofOutputsVectors } from './test-vectors/proof-request-queue/index.js';
import { sp1ConsensusMPTGroth16Proof } from './test-examples/sp1-mpt-proof/sp1ProofMessage.js';

// These vectors are generated by the Rust side and vendored here. They pin the
// encoding the SP1 guest and the Tempo contracts must agree on byte-for-byte.

const stripHexPrefix = (hex: string) => hex.slice(2);

const proofWithPublicValues = (hex: string) =>
    ({
        public_values: {
            buffer: { data: Array.from(Buffer.from(stripHexPrefix(hex), 'hex')) },
        },
    }) as unknown as NoriSP1ProofInput;

describe('ProofOutputs byte encoding', () => {
    test('vector set is populated', () => {
        expect(proofOutputsVectors.length).toBeGreaterThanOrEqual(3);
    });

    test.each(proofOutputsVectors.map((v) => [v.name, v] as const))(
        'decodes the Rust bytes for %s',
        (_name, vector) => {
            const decoded = decodeConsensusMptProof(proofWithPublicValues(vector.bytes));

            expect(decoded.inputSlot.toString()).toBe(vector.inputSlot);
            expect(decoded.inputStoreHash).toBe(vector.inputStoreHash);
            expect(decoded.outputSlot.toString()).toBe(vector.outputSlot);
            expect(decoded.outputStoreHash).toBe(vector.outputStoreHash);
            expect(decoded.executionStateRoot).toBe(vector.executionStateRoot);
            expect(decoded.verifiedRequestsRoot).toBe(vector.verifiedRequestsRoot);
            expect(decoded.nextSyncCommitteeHash).toBe(vector.nextSyncCommitteeHash);
            expect(decoded.proofRequestQueueAddress).toBe(vector.proofRequestQueueAddress);
            expect(decoded.inputQueueCursor.toString()).toBe(vector.inputQueueCursor);
            expect(decoded.outputQueueCursor.toString()).toBe(vector.outputQueueCursor);
            expect(decoded.outputBlockNumber.toString()).toBe(vector.outputBlockNumber);
        }
    );

    test('decode rejects a length other than 220 bytes', () => {
        const padded = `${proofOutputsVectors[0].bytes}${'00'.repeat(24)}`;
        expect(() => decodeConsensusMptProof(proofWithPublicValues(padded))).toThrow(/220/);
    });
});

describe('Example proof', () => {
    test('is made for the integrity program vkey', () => {
        expect(sp1ProgramVkey(sp1ConsensusMPTGroth16Proof)).toBe(bridgeHeadNoriSP1HeliosProgramVk);
    });

    test('drains no proof requests', () => {
        const decoded = decodeConsensusMptProof(sp1ConsensusMPTGroth16Proof);
        expect(decoded.inputQueueCursor).toBe(0n);
        expect(decoded.outputQueueCursor).toBe(0n);
    });

    test('gives the v6.1.0 verifier selector and 220-byte public values', () => {
        const proofBytes = sp1Groth16ProofBytes(sp1ConsensusMPTGroth16Proof);
        expect(proofBytes.slice(0, 10)).toBe('0x4388a21c');
        expect(stripHexPrefix(proofBytes).length / 2).toBe(356);
        expect(stripHexPrefix(sp1PublicValues(sp1ConsensusMPTGroth16Proof)).length / 2).toBe(220);
    });
});
