/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFeeManager } from './IFeeManager.js';
export type { ITIP20 } from './ITIP20.js';
export type { ITIP20Factory } from './ITIP20Factory.js';