/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface ITIP20FactoryInterface extends Interface {
    getFunction(nameOrSignature: "createToken" | "isTIP20"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TokenCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'createToken', values: [string, string, string, AddressLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'isTIP20', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'createToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTIP20', data: BytesLike): Result;
  }

  
    export namespace TokenCreatedEvent {
      export type InputTuple = [token: AddressLike, name: string, symbol: string, currency: string, quoteToken: AddressLike, admin: AddressLike, salt: BytesLike];
      export type OutputTuple = [token: string, name: string, symbol: string, currency: string, quoteToken: string, admin: string, salt: string];
      export interface OutputObject {token: string, name: string, symbol: string, currency: string, quoteToken: string, admin: string, salt: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ITIP20Factory extends BaseContract {
    
    connect(runner?: ContractRunner | null): ITIP20Factory;
    waitForDeployment(): Promise<this>;

    interface: ITIP20FactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createToken: TypedContractMethod<
      [name: string, symbol: string, currency: string, quoteToken: AddressLike, admin: AddressLike, salt: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    isTIP20: TypedContractMethod<
      [token: AddressLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createToken'): TypedContractMethod<
      [name: string, symbol: string, currency: string, quoteToken: AddressLike, admin: AddressLike, salt: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isTIP20'): TypedContractMethod<
      [token: AddressLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'TokenCreated'): TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;

    filters: {
      
      'TokenCreated(address,string,string,string,address,address,bytes32)': TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
      TokenCreated: TypedContractEvent<TokenCreatedEvent.InputTuple, TokenCreatedEvent.OutputTuple, TokenCreatedEvent.OutputObject>;
    
    };
  }