/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'IFeeManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IFeeManager__factory>
  getContractFactory(name: 'ITIP20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITIP20__factory>
  getContractFactory(name: 'ITIP20Factory', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITIP20Factory__factory>
  getContractFactory(name: 'NoriTempoTokenBridge', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoriTempoTokenBridge__factory>
  getContractFactory(name: 'PlonkVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PlonkVerifier__factory>
  getContractFactory(name: 'SP1Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SP1Verifier__factory>
  getContractFactory(name: 'SP1Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SP1Verifier__factory>
  getContractFactory(name: 'Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Verifier__factory>

  getContractAt(name: 'IFeeManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IFeeManager>
  getContractAt(name: 'ITIP20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITIP20>
  getContractAt(name: 'ITIP20Factory', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITIP20Factory>
  getContractAt(name: 'NoriTempoTokenBridge', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoriTempoTokenBridge>
  getContractAt(name: 'PlonkVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PlonkVerifier>
  getContractAt(name: 'SP1Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SP1Verifier>
  getContractAt(name: 'SP1Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SP1Verifier>
  getContractAt(name: 'Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Verifier>

  deployContract(name: 'IFeeManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeManager>
  deployContract(name: 'ITIP20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITIP20>
  deployContract(name: 'ITIP20Factory', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITIP20Factory>
  deployContract(name: 'NoriTempoTokenBridge', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoriTempoTokenBridge>
  deployContract(name: 'PlonkVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PlonkVerifier>
  deployContract(name: 'SP1Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SP1Verifier>
  deployContract(name: 'SP1Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SP1Verifier>
  deployContract(name: 'Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Verifier>

  deployContract(name: 'IFeeManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IFeeManager>
  deployContract(name: 'ITIP20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITIP20>
  deployContract(name: 'ITIP20Factory', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITIP20Factory>
  deployContract(name: 'NoriTempoTokenBridge', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoriTempoTokenBridge>
  deployContract(name: 'PlonkVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PlonkVerifier>
  deployContract(name: 'SP1Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SP1Verifier>
  deployContract(name: 'SP1Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SP1Verifier>
  deployContract(name: 'Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Verifier>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  