/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace NoriTempoTokenBridge {
      
    export type VerifiedRequestStruct = {target: AddressLike, collectionKeysCount: BigNumberish, collectionKeys: [BytesLike, BytesLike], value: BigNumberish}

    export type VerifiedRequestStructOutput = [target: string, collectionKeysCount: bigint, collectionKeys: [string, string], value: bigint] & {target: string, collectionKeysCount: bigint, collectionKeys: [string, string], value: bigint }
  

    export type VerifiedRequestWitnessStruct = {path: BytesLike[], index: BigNumberish, value: NoriTempoTokenBridge.VerifiedRequestStruct}

    export type VerifiedRequestWitnessStructOutput = [path: string[], index: bigint, value: NoriTempoTokenBridge.VerifiedRequestStructOutput] & {path: string[], index: bigint, value: NoriTempoTokenBridge.VerifiedRequestStructOutput }
  

    export type ProofOutputsStruct = {inputSlot: BigNumberish, inputStoreHash: BytesLike, outputSlot: BigNumberish, outputStoreHash: BytesLike, executionStateRoot: BytesLike, verifiedRequestsRoot: BytesLike, nextSyncCommitteeHash: BytesLike, proofRequestQueueAddress: AddressLike, inputQueueCursor: BigNumberish, outputQueueCursor: BigNumberish, outputBlockNumber: BigNumberish}

    export type ProofOutputsStructOutput = [inputSlot: bigint, inputStoreHash: string, outputSlot: bigint, outputStoreHash: string, executionStateRoot: string, verifiedRequestsRoot: string, nextSyncCommitteeHash: string, proofRequestQueueAddress: string, inputQueueCursor: bigint, outputQueueCursor: bigint, outputBlockNumber: bigint] & {inputSlot: bigint, inputStoreHash: string, outputSlot: bigint, outputStoreHash: string, executionStateRoot: string, verifiedRequestsRoot: string, nextSyncCommitteeHash: string, proofRequestQueueAddress: string, inputQueueCursor: bigint, outputQueueCursor: bigint, outputBlockNumber: bigint }
  

    export type ProofRequestRootEntryStruct = {root: BytesLike, outputBlockNumber: BigNumberish, inputQueueCursor: BigNumberish, outputQueueCursor: BigNumberish, tempoBlockNumber: BigNumberish}

    export type ProofRequestRootEntryStructOutput = [root: string, outputBlockNumber: bigint, inputQueueCursor: bigint, outputQueueCursor: bigint, tempoBlockNumber: bigint] & {root: string, outputBlockNumber: bigint, inputQueueCursor: bigint, outputQueueCursor: bigint, tempoBlockNumber: bigint }
  

    export type BridgeStateStruct = {verifiedStateRoot: BytesLike, latestHead: BigNumberish, noriBridgeVk: BytesLike, latestHeliosStoreInputHash: BytesLike, ethProofQueueAddress: AddressLike, ethTokenBridgeAddress: AddressLike, queueCursor: BigNumberish, proofQueueBatchCount: BigNumberish}

    export type BridgeStateStructOutput = [verifiedStateRoot: string, latestHead: bigint, noriBridgeVk: string, latestHeliosStoreInputHash: string, ethProofQueueAddress: string, ethTokenBridgeAddress: string, queueCursor: bigint, proofQueueBatchCount: bigint] & {verifiedStateRoot: string, latestHead: bigint, noriBridgeVk: string, latestHeliosStoreInputHash: string, ethProofQueueAddress: string, ethTokenBridgeAddress: string, queueCursor: bigint, proofQueueBatchCount: bigint }
  
    }

  export interface NoriTempoTokenBridgeInterface extends Interface {
    getFunction(nameOrSignature: "ISSUER_ROLE" | "MAX_BATCH" | "MAX_COLLECTION_KEYS" | "MAX_TREE_DEPTH" | "PATH_USD" | "PAUSE_KEY" | "PAUSE_ROLE" | "PAUSE_STATE_PAUSED" | "PAUSE_STATE_UNPAUSED" | "PROOF_OUTPUTS_SIZE" | "TIP20_FACTORY" | "UNPAUSE_ROLE" | "applyPause" | "decodeProofOutputs" | "erc20MintedSoFar" | "ethProofQueueAddress" | "ethTokenBridgeAddress" | "findProofQueueBatch" | "lastPauseApplied" | "latestHead" | "latestHeliosStoreInputHash" | "mint" | "mintERC20" | "mintedSoFar" | "mirrorAdmin" | "mirrorOf" | "noriBridgeVk" | "proofQueueBatch" | "proofQueueBatchCount" | "proofQueueBatches" | "queueCursor" | "registerMirror" | "requestLeafHash" | "state" | "token" | "update" | "verifiedRequestWitnessRoot" | "verifiedStateRoot" | "verifier"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ERC20MintApplied" | "MintApplied" | "MirrorRegistered" | "PauseApplied" | "ProofQueueBatchCommitted" | "UpdateApplied"): EventFragment;

    encodeFunctionData(functionFragment: 'ISSUER_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_BATCH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_COLLECTION_KEYS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_TREE_DEPTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'PATH_USD', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_KEY', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_STATE_PAUSED', values?: undefined): string;
encodeFunctionData(functionFragment: 'PAUSE_STATE_UNPAUSED', values?: undefined): string;
encodeFunctionData(functionFragment: 'PROOF_OUTPUTS_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'TIP20_FACTORY', values?: undefined): string;
encodeFunctionData(functionFragment: 'UNPAUSE_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'applyPause', values: [NoriTempoTokenBridge.VerifiedRequestWitnessStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'decodeProofOutputs', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'erc20MintedSoFar', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'ethProofQueueAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'ethTokenBridgeAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'findProofQueueBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lastPauseApplied', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'latestHead', values?: undefined): string;
encodeFunctionData(functionFragment: 'latestHeliosStoreInputHash', values?: undefined): string;
encodeFunctionData(functionFragment: 'mint', values: [NoriTempoTokenBridge.VerifiedRequestWitnessStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintERC20', values: [NoriTempoTokenBridge.VerifiedRequestWitnessStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'mintedSoFar', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'mirrorAdmin', values?: undefined): string;
encodeFunctionData(functionFragment: 'mirrorOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'noriBridgeVk', values?: undefined): string;
encodeFunctionData(functionFragment: 'proofQueueBatch', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'proofQueueBatchCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'proofQueueBatches', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'queueCursor', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerMirror', values: [AddressLike, string, string, string, BytesLike]): string;
encodeFunctionData(functionFragment: 'requestLeafHash', values: [NoriTempoTokenBridge.VerifiedRequestStruct]): string;
encodeFunctionData(functionFragment: 'state', values?: undefined): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'update', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'verifiedRequestWitnessRoot', values: [NoriTempoTokenBridge.VerifiedRequestWitnessStruct]): string;
encodeFunctionData(functionFragment: 'verifiedStateRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'ISSUER_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_BATCH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_COLLECTION_KEYS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_TREE_DEPTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PATH_USD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_KEY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_STATE_PAUSED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PAUSE_STATE_UNPAUSED', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PROOF_OUTPUTS_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TIP20_FACTORY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'UNPAUSE_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'applyPause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decodeProofOutputs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'erc20MintedSoFar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethProofQueueAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethTokenBridgeAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'findProofQueueBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastPauseApplied', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestHead', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latestHeliosStoreInputHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintERC20', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintedSoFar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mirrorAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mirrorOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'noriBridgeVk', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofQueueBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofQueueBatchCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'proofQueueBatches', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'queueCursor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerMirror', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestLeafHash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'state', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'update', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiedRequestWitnessRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiedStateRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier', data: BytesLike): Result;
  }

  
    export namespace ERC20MintAppliedEvent {
      export type InputTuple = [ethToken: AddressLike, recipient: AddressLike, depositRoot: BytesLike, amountMinted: BigNumberish, mintedSoFar: BigNumberish];
      export type OutputTuple = [ethToken: string, recipient: string, depositRoot: string, amountMinted: bigint, mintedSoFar: bigint];
      export interface OutputObject {ethToken: string, recipient: string, depositRoot: string, amountMinted: bigint, mintedSoFar: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MintAppliedEvent {
      export type InputTuple = [recipient: AddressLike, depositRoot: BytesLike, amountMinted: BigNumberish, mintedSoFar: BigNumberish];
      export type OutputTuple = [recipient: string, depositRoot: string, amountMinted: bigint, mintedSoFar: bigint];
      export interface OutputObject {recipient: string, depositRoot: string, amountMinted: bigint, mintedSoFar: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MirrorRegisteredEvent {
      export type InputTuple = [ethToken: AddressLike, mirror: AddressLike, name: string, symbol: string];
      export type OutputTuple = [ethToken: string, mirror: string, name: string, symbol: string];
      export interface OutputObject {ethToken: string, mirror: string, name: string, symbol: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PauseAppliedEvent {
      export type InputTuple = [ethToken: AddressLike, mirror: AddressLike, paused: boolean, proofQueueBatchIndex: BigNumberish];
      export type OutputTuple = [ethToken: string, mirror: string, paused: boolean, proofQueueBatchIndex: bigint];
      export interface OutputObject {ethToken: string, mirror: string, paused: boolean, proofQueueBatchIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProofQueueBatchCommittedEvent {
      export type InputTuple = [proofQueueBatchIndex: BigNumberish, root: BytesLike, inputQueueCursor: BigNumberish, outputQueueCursor: BigNumberish, outputBlockNumber: BigNumberish];
      export type OutputTuple = [proofQueueBatchIndex: bigint, root: string, inputQueueCursor: bigint, outputQueueCursor: bigint, outputBlockNumber: bigint];
      export interface OutputObject {proofQueueBatchIndex: bigint, root: string, inputQueueCursor: bigint, outputQueueCursor: bigint, outputBlockNumber: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UpdateAppliedEvent {
      export type InputTuple = [outputSlot: BigNumberish, queueCursor: BigNumberish, verifiedStateRoot: BytesLike, proofQueueBatchCount: BigNumberish];
      export type OutputTuple = [outputSlot: bigint, queueCursor: bigint, verifiedStateRoot: string, proofQueueBatchCount: bigint];
      export interface OutputObject {outputSlot: bigint, queueCursor: bigint, verifiedStateRoot: string, proofQueueBatchCount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface NoriTempoTokenBridge extends BaseContract {
    
    connect(runner?: ContractRunner | null): NoriTempoTokenBridge;
    waitForDeployment(): Promise<this>;

    interface: NoriTempoTokenBridgeInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ISSUER_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    MAX_BATCH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_COLLECTION_KEYS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_TREE_DEPTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PATH_USD: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_KEY: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    PAUSE_STATE_PAUSED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PAUSE_STATE_UNPAUSED: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PROOF_OUTPUTS_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TIP20_FACTORY: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    UNPAUSE_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    applyPause: TypedContractMethod<
      [pauseWitness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, proofQueueBatchIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    decodeProofOutputs: TypedContractMethod<
      [publicValues: BytesLike, ],
      [NoriTempoTokenBridge.ProofOutputsStructOutput],
      'view'
    >
    

    
    erc20MintedSoFar: TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    ethProofQueueAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ethTokenBridgeAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    findProofQueueBatch: TypedContractMethod<
      [requestId: BigNumberish, ],
      [[bigint, NoriTempoTokenBridge.ProofRequestRootEntryStructOutput] & {proofQueueBatchIndex: bigint, batch: NoriTempoTokenBridge.ProofRequestRootEntryStructOutput }],
      'view'
    >
    

    
    lastPauseApplied: TypedContractMethod<
      [ethToken: AddressLike, ],
      [[boolean, bigint] & {applied: boolean, proofQueueBatchIndex: bigint }],
      'view'
    >
    

    
    latestHead: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latestHeliosStoreInputHash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mint: TypedContractMethod<
      [depositWitness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, proofQueueBatchIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mintERC20: TypedContractMethod<
      [depositWitness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, proofQueueBatchIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    mintedSoFar: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    mirrorAdmin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    mirrorOf: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    noriBridgeVk: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    proofQueueBatch: TypedContractMethod<
      [proofQueueBatchIndex: BigNumberish, ],
      [NoriTempoTokenBridge.ProofRequestRootEntryStructOutput],
      'view'
    >
    

    
    proofQueueBatchCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    proofQueueBatches: TypedContractMethod<
      [fromIndex: BigNumberish, count: BigNumberish, ],
      [NoriTempoTokenBridge.ProofRequestRootEntryStructOutput[]],
      'view'
    >
    

    
    queueCursor: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    registerMirror: TypedContractMethod<
      [ethToken: AddressLike, name: string, symbol: string, currency: string, salt: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    requestLeafHash: TypedContractMethod<
      [request: NoriTempoTokenBridge.VerifiedRequestStruct, ],
      [string],
      'view'
    >
    

    
    state: TypedContractMethod<
      [],
      [NoriTempoTokenBridge.BridgeStateStructOutput],
      'view'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    update: TypedContractMethod<
      [proof: BytesLike, sp1PublicInputs: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    verifiedRequestWitnessRoot: TypedContractMethod<
      [witness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, ],
      [string],
      'view'
    >
    

    
    verifiedStateRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ISSUER_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_BATCH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_COLLECTION_KEYS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_TREE_DEPTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PATH_USD'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_KEY'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_STATE_PAUSED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PAUSE_STATE_UNPAUSED'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PROOF_OUTPUTS_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TIP20_FACTORY'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'UNPAUSE_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'applyPause'): TypedContractMethod<
      [pauseWitness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, proofQueueBatchIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decodeProofOutputs'): TypedContractMethod<
      [publicValues: BytesLike, ],
      [NoriTempoTokenBridge.ProofOutputsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'erc20MintedSoFar'): TypedContractMethod<
      [arg0: AddressLike, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'ethProofQueueAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ethTokenBridgeAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'findProofQueueBatch'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [[bigint, NoriTempoTokenBridge.ProofRequestRootEntryStructOutput] & {proofQueueBatchIndex: bigint, batch: NoriTempoTokenBridge.ProofRequestRootEntryStructOutput }],
      'view'
    >;
getFunction(nameOrSignature: 'lastPauseApplied'): TypedContractMethod<
      [ethToken: AddressLike, ],
      [[boolean, bigint] & {applied: boolean, proofQueueBatchIndex: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'latestHead'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latestHeliosStoreInputHash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mint'): TypedContractMethod<
      [depositWitness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, proofQueueBatchIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintERC20'): TypedContractMethod<
      [depositWitness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, proofQueueBatchIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintedSoFar'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'mirrorAdmin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'mirrorOf'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'noriBridgeVk'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'proofQueueBatch'): TypedContractMethod<
      [proofQueueBatchIndex: BigNumberish, ],
      [NoriTempoTokenBridge.ProofRequestRootEntryStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'proofQueueBatchCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'proofQueueBatches'): TypedContractMethod<
      [fromIndex: BigNumberish, count: BigNumberish, ],
      [NoriTempoTokenBridge.ProofRequestRootEntryStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'queueCursor'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'registerMirror'): TypedContractMethod<
      [ethToken: AddressLike, name: string, symbol: string, currency: string, salt: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestLeafHash'): TypedContractMethod<
      [request: NoriTempoTokenBridge.VerifiedRequestStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'state'): TypedContractMethod<
      [],
      [NoriTempoTokenBridge.BridgeStateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'update'): TypedContractMethod<
      [proof: BytesLike, sp1PublicInputs: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifiedRequestWitnessRoot'): TypedContractMethod<
      [witness: NoriTempoTokenBridge.VerifiedRequestWitnessStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifiedStateRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'ERC20MintApplied'): TypedContractEvent<ERC20MintAppliedEvent.InputTuple, ERC20MintAppliedEvent.OutputTuple, ERC20MintAppliedEvent.OutputObject>;
getEvent(key: 'MintApplied'): TypedContractEvent<MintAppliedEvent.InputTuple, MintAppliedEvent.OutputTuple, MintAppliedEvent.OutputObject>;
getEvent(key: 'MirrorRegistered'): TypedContractEvent<MirrorRegisteredEvent.InputTuple, MirrorRegisteredEvent.OutputTuple, MirrorRegisteredEvent.OutputObject>;
getEvent(key: 'PauseApplied'): TypedContractEvent<PauseAppliedEvent.InputTuple, PauseAppliedEvent.OutputTuple, PauseAppliedEvent.OutputObject>;
getEvent(key: 'ProofQueueBatchCommitted'): TypedContractEvent<ProofQueueBatchCommittedEvent.InputTuple, ProofQueueBatchCommittedEvent.OutputTuple, ProofQueueBatchCommittedEvent.OutputObject>;
getEvent(key: 'UpdateApplied'): TypedContractEvent<UpdateAppliedEvent.InputTuple, UpdateAppliedEvent.OutputTuple, UpdateAppliedEvent.OutputObject>;

    filters: {
      
      'ERC20MintApplied(address,address,bytes32,uint64,uint64)': TypedContractEvent<ERC20MintAppliedEvent.InputTuple, ERC20MintAppliedEvent.OutputTuple, ERC20MintAppliedEvent.OutputObject>;
      ERC20MintApplied: TypedContractEvent<ERC20MintAppliedEvent.InputTuple, ERC20MintAppliedEvent.OutputTuple, ERC20MintAppliedEvent.OutputObject>;
    

      'MintApplied(address,bytes32,uint64,uint64)': TypedContractEvent<MintAppliedEvent.InputTuple, MintAppliedEvent.OutputTuple, MintAppliedEvent.OutputObject>;
      MintApplied: TypedContractEvent<MintAppliedEvent.InputTuple, MintAppliedEvent.OutputTuple, MintAppliedEvent.OutputObject>;
    

      'MirrorRegistered(address,address,string,string)': TypedContractEvent<MirrorRegisteredEvent.InputTuple, MirrorRegisteredEvent.OutputTuple, MirrorRegisteredEvent.OutputObject>;
      MirrorRegistered: TypedContractEvent<MirrorRegisteredEvent.InputTuple, MirrorRegisteredEvent.OutputTuple, MirrorRegisteredEvent.OutputObject>;
    

      'PauseApplied(address,address,bool,uint64)': TypedContractEvent<PauseAppliedEvent.InputTuple, PauseAppliedEvent.OutputTuple, PauseAppliedEvent.OutputObject>;
      PauseApplied: TypedContractEvent<PauseAppliedEvent.InputTuple, PauseAppliedEvent.OutputTuple, PauseAppliedEvent.OutputObject>;
    

      'ProofQueueBatchCommitted(uint64,bytes32,uint64,uint64,uint64)': TypedContractEvent<ProofQueueBatchCommittedEvent.InputTuple, ProofQueueBatchCommittedEvent.OutputTuple, ProofQueueBatchCommittedEvent.OutputObject>;
      ProofQueueBatchCommitted: TypedContractEvent<ProofQueueBatchCommittedEvent.InputTuple, ProofQueueBatchCommittedEvent.OutputTuple, ProofQueueBatchCommittedEvent.OutputObject>;
    

      'UpdateApplied(uint64,uint64,bytes32,uint64)': TypedContractEvent<UpdateAppliedEvent.InputTuple, UpdateAppliedEvent.OutputTuple, UpdateAppliedEvent.OutputObject>;
      UpdateApplied: TypedContractEvent<UpdateAppliedEvent.InputTuple, UpdateAppliedEvent.OutputTuple, UpdateAppliedEvent.OutputObject>;
    
    };
  }